from typing import Any

import pytest
from glasshat.rubric.models import Criterion, SynthesizedRubric, ThresholdGate
from pydantic import ValidationError as PydErr


def _crit(**kw: Any) -> Criterion:
    base: dict[str, Any] = dict(
        id="tech-implementation",
        label="Tech",
        weight=0.25,
        scale=5,
        bmad_mapping=["C1"],
        descriptor_levels={1: "a", 2: "b", 3: "c", 4: "d", 5: "e"},
        evidence_required=True,
        source_clause="x",
        source_excerpt="y",
    )
    base.update(kw)
    return Criterion(**base)


def _rubric_dict(criteria: list[Criterion], aggregation: str) -> dict[str, Any]:
    return dict(
        schema_version="1.0",
        source={"type": "preset", "identifier": "test"},
        scoring_rule={"aggregation": aggregation, "final_scale": "0-100"},
        criteria=[c.model_dump() for c in criteria],
        tie_breakers=[],
        threshold_gates=[],
        confidence=1.0,
    )


def test_valid_criterion() -> None:
    c = _crit()
    assert c.id == "tech-implementation" and c.scale == 5


def test_descriptor_levels_must_cover_scale() -> None:
    with pytest.raises(PydErr):
        _crit(descriptor_levels={1: "a", 2: "b", 3: "c"})  # missing 4,5


def test_bmad_mapping_nonempty() -> None:
    with pytest.raises(PydErr):
        _crit(bmad_mapping=[])


def test_bmad_mapping_must_be_valid_primitive() -> None:
    with pytest.raises(PydErr):
        _crit(bmad_mapping=["Z9"])


def test_weighted_sum_weights_must_total_one() -> None:
    good = [_crit(id=f"c{i}", weight=0.25) for i in range(4)]
    r = SynthesizedRubric.model_validate(_rubric_dict(good, "weighted_sum"))
    assert abs(sum(c.weight or 0 for c in r.criteria) - 1.0) < 0.01

    with pytest.raises(PydErr):
        bad = [_crit(id=f"c{i}", weight=0.5) for i in range(4)]  # sums to 2.0
        SynthesizedRubric.model_validate(_rubric_dict(bad, "weighted_sum"))


def test_simple_average_allows_equal_weights() -> None:
    crits = [_crit(id=f"c{i}", weight=0.333) for i in range(3)]
    r = SynthesizedRubric.model_validate(_rubric_dict(crits, "simple_average"))
    assert r.scoring_rule.aggregation == "simple_average"


def test_tie_breaker_must_reference_existing_criterion() -> None:
    crits = [_crit(id="tech-implementation", weight=0.5), _crit(id="design", weight=0.5)]
    d = _rubric_dict(crits, "weighted_sum")
    d["tie_breakers"] = [{"order": 1, "criterion_id": "does-not-exist"}]
    with pytest.raises(PydErr):
        SynthesizedRubric.model_validate(d)


def test_rubric_id_autogenerated() -> None:
    crits = [_crit(id=f"c{i}", weight=0.5) for i in range(2)]
    r = SynthesizedRubric.model_validate(_rubric_dict(crits, "weighted_sum"))
    assert len(r.rubric_id) == 36


def test_thresholdgate_invalid_check_raises() -> None:
    with pytest.raises(PydErr):
        ThresholdGate(id="x", condition="y", check="bogus")


def test_weighted_sum_requires_weight_on_every_criterion() -> None:
    crits = [_crit(id="a", weight=None), _crit(id="b", weight=1.0)]
    with pytest.raises(PydErr):
        SynthesizedRubric.model_validate(_rubric_dict(crits, "weighted_sum"))


def test_simple_average_rejects_unequal_weights() -> None:
    crits = [_crit(id="a", weight=0.5), _crit(id="b", weight=0.3)]
    with pytest.raises(PydErr):
        SynthesizedRubric.model_validate(_rubric_dict(crits, "simple_average"))


def test_duplicate_tie_breaker_order_raises() -> None:
    crits = [_crit(id="a", weight=0.5), _crit(id="b", weight=0.5)]
    d = _rubric_dict(crits, "weighted_sum")
    d["tie_breakers"] = [
        {"order": 1, "criterion_id": "a"},
        {"order": 1, "criterion_id": "b"},
    ]
    with pytest.raises(PydErr):
        SynthesizedRubric.model_validate(d)


def test_large_scale_skips_descriptor_coverage() -> None:
    # scale > 10 (e.g. 0-100 band scale) does not require a descriptor per integer
    c = _crit(scale=100, descriptor_levels={1: "low", 50: "mid", 100: "high"})
    assert c.scale == 100
